--DRR cleanup script for automated test data
delete from account where name like 'autotest-%'
delete from drr_criticalinfrastructureimpacted where drr_name like 'autotest-%'
delete from contact where lastname like 'autotest-%'
delete from drr_fundingsource where drr_name like 'autotest%'
delete from drr_application where drr_primary_proponent_name is null
delete from drr_application where drr_primary_proponent_namename like 'autotest%'
delete from drr_application where drr_primary_proponent_namename is null
delete from drr_proposedactivity where drr_name like 'autotest%'
delete from bcgov_documenturl where bcgov_filename like 'autotest%'
delete from bcgov_documenturl where bcgov_application is null
delete from drr_driffundingrequest where drr_application is null
delete from drr_costconsiderationitem where drr_application is null
delete from drr_resiliencyitem where drr_application is null
delete from drr_climateassessmenttoolitem where drr_application is null
delete from drr_projectcapacitychallengeitem where drr_application is null
delete from drr_projectsensitivityriskitem where drr_application is null
delete from drr_projectreadinessriskitem where drr_application is null
delete from drr_projectcomplexityriskitem where drr_application is null
delete from drr_cobenefititem where drr_application is null
delete from drr_costreductionitem where drr_application is null
delete from drr_foundationalorpreviousworkitem where drr_application is null
delete from drr_impactedoraffectedpartyitem where drr_application is null
delete from drr_provincialstandarditem where drr_application is null
delete from drr_qualifiedprofessionalitem where drr_application is null