/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type Actions = typeof Actions[keyof typeof Actions];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Actions = {
  CreateFP: 'CreateFP',
  Delete: 'Delete',
  Edit: 'Edit',
  Withdraw: 'Withdraw',
} as const;
