/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type ApplicationType = typeof ApplicationType[keyof typeof ApplicationType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApplicationType = {
  EOI: 'EOI',
  FP: 'FP',
} as const;
