/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type ApplicationStatus = typeof ApplicationStatus[keyof typeof ApplicationStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApplicationStatus = {
  Draft: 'Draft',
  Submitted: 'Submitted',
  Rejected: 'Rejected',
} as const;
