/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type AreaUnits = typeof AreaUnits[keyof typeof AreaUnits];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AreaUnits = {
  Hectares: 'Hectares',
  Acres: 'Acres',
  SqKm: 'SqKm',
} as const;
