/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type AreaUnits = typeof AreaUnits[keyof typeof AreaUnits];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AreaUnits = {
  m2: 'm2',
  ha: 'ha',
} as const;
