/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentType } from './documentType';

export interface Attachment {
  applicationId?: string;
  /** @nullable */
  comments?: string;
  content?: string;
  contentType?: string;
  documentType?: DocumentType;
  /** @nullable */
  haveResolution?: boolean;
  /** @nullable */
  id?: string;
  name?: string;
}
