/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { ReportType } from './reportType';

export interface CanCreateReportResult {
  canCreate?: boolean;
  /** @nullable */
  description?: string;
  reportType?: ReportType;
}
