/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { OidcConfiguration } from './oidcConfiguration';

export interface Configuration {
  oidc?: OidcConfiguration;
}
