/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export interface ContactDetails {
  /**
   * @minLength 0
   * @maxLength 40
   */
  department?: string;
  /**
   * @minLength 0
   * @maxLength 40
   */
  email?: string;
  /**
   * @minLength 0
   * @maxLength 40
   */
  firstName?: string;
  /**
   * @minLength 0
   * @maxLength 40
   */
  lastName?: string;
  phone?: string;
  /**
   * @minLength 0
   * @maxLength 40
   */
  title?: string;
}
