/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export interface ContactDetails {
  department?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  phone?: string;
  title?: string;
}
