/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export interface ContactDetails {
  /**
   * @minLength 0
   * @maxLength 40
   * @nullable
   */
  department?: string;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  email?: string;
  /**
   * @minLength 0
   * @maxLength 40
   * @nullable
   */
  firstName?: string;
  /** @nullable */
  id?: string;
  /**
   * @minLength 0
   * @maxLength 40
   * @nullable
   */
  lastName?: string;
  /** @nullable */
  phone?: string;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  title?: string;
}
