/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type CostUnit = (typeof CostUnit)[keyof typeof CostUnit];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CostUnit = {
  Hours: 'Hours',
  LumpSum: 'LumpSum',
  Each: 'Each',
  Metre: 'Metre',
  SquareMetre: 'SquareMetre',
  CubicMetre: 'CubicMetre',
  Kilometer: 'Kilometer',
  SquareKilometer: 'SquareKilometer',
  Hectare: 'Hectare',
  Kilogram: 'Kilogram',
  Tonne: 'Tonne',
  Other: 'Other',
} as const;
