/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type CostUnit = typeof CostUnit[keyof typeof CostUnit];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CostUnit = {
  Unit1: 'Unit1',
  Unit2: 'Unit2',
  Unit3: 'Unit3',
} as const;
