/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type CostEstimateClass =
  (typeof CostEstimateClass)[keyof typeof CostEstimateClass];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CostEstimateClass = {
  ClassA: 'ClassA',
  ClassB: 'ClassB',
} as const;
