/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { CostCategory } from './costCategory';
import type { ResourceCategory } from './resourceCategory';
import type { CostUnit } from './costUnit';

export interface CostEstimate {
  /** @nullable */
  costCategory?: CostCategory;
  /** @nullable */
  description?: string;
  /** @nullable */
  quantity?: number;
  /** @nullable */
  resources?: ResourceCategory;
  /** @nullable */
  taskName?: string;
  /** @nullable */
  totalCost?: number;
  /** @nullable */
  unitRate?: number;
  /** @nullable */
  units?: CostUnit;
}
