/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type CostCategory = (typeof CostCategory)[keyof typeof CostCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CostCategory = {
  ProjectAdministration: 'ProjectAdministration',
  ProjectPlanning: 'ProjectPlanning',
  Design: 'Design',
  Assessment: 'Assessment',
  Mapping: 'Mapping',
  ConstructionMaterials: 'ConstructionMaterials',
  FirstNationsEngagement: 'FirstNationsEngagement',
  NeighbouringJurisdictions: 'NeighbouringJurisdictions',
  ProponentCommunities: 'ProponentCommunities',
  IncrementalStaffing: 'IncrementalStaffing',
  ShortTermInterest: 'ShortTermInterest',
  LandAcquisition: 'LandAcquisition',
  Communications: 'Communications',
  ApprovalsPermitting: 'ApprovalsPermitting',
  Contingency: 'Contingency',
  Other: 'Other',
} as const;
