/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { ApplicationStatus } from './applicationStatus';

export interface CRAFTApplication {
  createdTime?: string;
  id?: string;
  projectTitle?: string;
  status?: ApplicationStatus;
}
