/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { DeclarationInfo } from './declarationInfo';

export interface DeclarationResult {
  items?: DeclarationInfo[];
}
