/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type DeclarationType =
  (typeof DeclarationType)[keyof typeof DeclarationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeclarationType = {
  AuthorizedRepresentative: 'AuthorizedRepresentative',
  AccuracyOfInformation: 'AccuracyOfInformation',
} as const;
