/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type Delay = (typeof Delay)[keyof typeof Delay];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Delay = {
  Tendering: 'Tendering',
  Referendum: 'Referendum',
  PropertyAquisition: 'PropertyAquisition',
  Negotiations: 'Negotiations',
  ProjectImplementation: 'ProjectImplementation',
  UnforeseenComplexity: 'UnforeseenComplexity',
  ProjectScopeChange: 'ProjectScopeChange',
  GovernmentAgencies: 'GovernmentAgencies',
  UnforeseenContractorDelays: 'UnforeseenContractorDelays',
  Weather: 'Weather',
  ChangeProjectManager: 'ChangeProjectManager',
  Other: 'Other',
} as const;
