/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type DocumentType = typeof DocumentType[keyof typeof DocumentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DocumentType = {
  ProponentEligibilitySupportingDocument: 'ProponentEligibilitySupportingDocument',
  ProjectEligibilitySupportingDocument: 'ProjectEligibilitySupportingDocument',
  ProjectWorkplan: 'ProjectWorkplan',
  ProjectSchedule: 'ProjectSchedule',
  SitePlan: 'SitePlan',
  PreliminaryDesign: 'PreliminaryDesign',
  ProjectDetailsSupportingDocument: 'ProjectDetailsSupportingDocument',
  CostEstimate: 'CostEstimate',
  BudgetSupportingDocument: 'BudgetSupportingDocument',
} as const;
