/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type DocumentType = typeof DocumentType[keyof typeof DocumentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DocumentType = {
  DetailedProjectWorkplan: 'DetailedProjectWorkplan',
  ProjectSchedule: 'ProjectSchedule',
  DetailedCostEstimate: 'DetailedCostEstimate',
  SitePlan: 'SitePlan',
  PreliminaryDesign: 'PreliminaryDesign',
  FirstNationsResolution: 'FirstNationsResolution',
  LocalGovernmentResolution: 'LocalGovernmentResolution',
  OtherSupportingDocument: 'OtherSupportingDocument',
} as const;
