/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { DraftApplication } from './draftApplication';
import type { DraftEoiApplicationAllOf } from './draftEoiApplicationAllOf';

export type DraftEoiApplication = DraftApplication & DraftEoiApplicationAllOf;
