/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { Attachment } from './attachment';
import type { YesNoOption } from './yesNoOption';
import type { ProposedActivity } from './proposedActivity';
import type { StandardInfo } from './standardInfo';
import type { AreaUnits } from './areaUnits';
import type { YearOverYearFunding } from './yearOverYearFunding';

export type DraftFpApplicationAllOf = {
  /** @nullable */
  activityCostEffectiveness?: string;
  /** @nullable */
  affectedParties?: string[];
  /** @nullable */
  approvals?: boolean;
  /** @nullable */
  approvalsComments?: string;
  /** @nullable */
  area?: number;
  /** @nullable */
  areaDescription?: string;
  /** @nullable */
  attachments?: Attachment[];
  /** @nullable */
  authorizationOrEndorsementComments?: string;
  /** @nullable */
  capacityRiskComments?: string;
  /** @nullable */
  capacityRiskMitigated?: boolean;
  /** @nullable */
  capacityRisks?: string[];
  /** @nullable */
  coBenefitComments?: string;
  /** @nullable */
  coBenefits?: string[];
  /** @nullable */
  collaborationComments?: string;
  /** @nullable */
  complexityRiskComments?: string;
  /** @nullable */
  complexityRiskMitigated?: boolean;
  /** @nullable */
  complexityRisks?: string[];
  /** @nullable */
  costConsiderations?: string[];
  /** @nullable */
  costConsiderationsApplied?: boolean;
  /** @nullable */
  costConsiderationsComments?: string;
  /** @nullable */
  costEffective?: boolean;
  /** @nullable */
  costEffectiveComments?: string;
  /** @nullable */
  costReductionComments?: string;
  /** @nullable */
  costReductions?: string[];
  /** @nullable */
  discrepancyComment?: string;
  /** @nullable */
  engagedWithFirstNationsComments?: string;
  /** @nullable */
  engagedWithFirstNationsOccurred?: boolean;
  /** @nullable */
  eoiId?: string;
  /** @nullable */
  firstNationsAuthorizedByPartners?: YesNoOption;
  /** @nullable */
  futureCostReduction?: boolean;
  /** @nullable */
  haveAuthorityToDevelop?: boolean;
  /** @nullable */
  incorporateFutureClimateConditions?: boolean;
  /** @nullable */
  increasedResiliency?: string[];
  /** @nullable */
  increasedResiliencyComments?: string;
  /** @nullable */
  isInfrastructureImpacted?: boolean;
  /** @nullable */
  localGovernmentAuthorizedByPartners?: YesNoOption;
  /** @nullable */
  mainDeliverable?: string;
  /** @nullable */
  meetsEligibilityComments?: string;
  /** @nullable */
  meetsEligibilityRequirements?: boolean;
  /** @nullable */
  meetsRegulatoryComments?: string;
  /** @nullable */
  meetsRegulatoryRequirements?: boolean;
  /** @nullable */
  operationAndMaintenance?: YesNoOption;
  /** @nullable */
  operationAndMaintenanceComments?: string;
  /** @nullable */
  otherEngagement?: YesNoOption;
  /** @nullable */
  otherEngagementComments?: string;
  /** @nullable */
  previousResponse?: YesNoOption;
  /** @nullable */
  previousResponseComments?: string;
  /** @nullable */
  previousResponseCost?: number;
  /** @nullable */
  produceCoBenefits?: boolean;
  /** @nullable */
  professionalGuidance?: boolean;
  /** @nullable */
  professionalGuidanceComments?: string;
  /** @nullable */
  professionals?: string[];
  /** @nullable */
  projectAlternateOptions?: string;
  /** @nullable */
  projectDescription?: string;
  /** @nullable */
  proposedActivities?: ProposedActivity[];
  /** @nullable */
  publicBenefit?: boolean;
  /** @nullable */
  publicBenefitComments?: string;
  /** @nullable */
  readinessRiskComments?: string;
  /** @nullable */
  readinessRiskMitigated?: boolean;
  /** @nullable */
  readinessRisks?: string[];
  /** @nullable */
  regionalProject?: boolean;
  /** @nullable */
  regionalProjectComments?: string;
  /** @nullable */
  riskTransferMigigated?: boolean;
  /** @nullable */
  sensitivityRiskComments?: string;
  /** @nullable */
  sensitivityRiskMitigated?: boolean;
  /** @nullable */
  sensitivityRisks?: string[];
  /** @nullable */
  standards?: StandardInfo[];
  /** @nullable */
  standardsAcceptable?: YesNoOption;
  /** @nullable */
  standardsComments?: string;
  /**
   * @minimum 0
   * @maximum 999999999.99
   * @nullable
   */
  totalDrifFundingRequest?: number;
  /** @nullable */
  transferRisks?: string[];
  /** @nullable */
  transferRisksComments?: string;
  /** @nullable */
  units?: AreaUnits;
  /** @nullable */
  verificationMethods?: string[];
  /** @nullable */
  verificationMethodsComments?: string;
  /** @nullable */
  yearOverYearFunding?: YearOverYearFunding[];
};
