/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { ContactDetails } from './contactDetails';

export interface DraftApplication {
  additionalContacts?: ContactDetails[];
}
