/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { StandardInfo } from './standardInfo';

export interface EntitiesQueryResult {
  /** @nullable */
  affectedParties?: string[];
  /** @nullable */
  capacityRisks?: string[];
  /** @nullable */
  climateAssessmentToolOptions?: string[];
  /** @nullable */
  coBenefits?: string[];
  /** @nullable */
  complexityRisks?: string[];
  /** @nullable */
  costConsiderations?: string[];
  /** @nullable */
  costReductions?: string[];
  /** @nullable */
  fiscalYears?: string[];
  /** @nullable */
  foundationalOrPreviousWorks?: string[];
  /** @nullable */
  increasedResiliency?: string[];
  /** @nullable */
  professionals?: string[];
  /** @nullable */
  projectActivities?: string[];
  /** @nullable */
  readinessRisks?: string[];
  /** @nullable */
  sensitivityRisks?: string[];
  /** @nullable */
  standards?: StandardInfo[];
}
