/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { Standards } from './standards';

export interface EntitiesQueryResult {
  /** @nullable */
  affectedParties?: string[];
  /** @nullable */
  capacityRisks?: string[];
  /** @nullable */
  coBenefits?: string[];
  /** @nullable */
  complexityRisks?: string[];
  /** @nullable */
  costConsiderations?: string[];
  /** @nullable */
  costReductions?: string[];
  /** @nullable */
  fiscalYears?: string[];
  /** @nullable */
  increasedResiliency?: string[];
  /** @nullable */
  professionals?: string[];
  /** @nullable */
  readinessRisks?: string[];
  /** @nullable */
  sensitivityRisks?: string[];
  /** @nullable */
  standardCategories?: string[];
  /** @nullable */
  standards?: Standards[];
  /** @nullable */
  verificationMethods?: string[];
}
