/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export interface EntitiesQueryResult {
  /** @nullable */
  affectedParties?: string[];
  /** @nullable */
  capacityRisks?: string[];
  /** @nullable */
  complexityRisks?: string[];
  /** @nullable */
  fiscalYears?: string[];
  /** @nullable */
  readinessRisks?: string[];
  /** @nullable */
  sensitivityRisks?: string[];
  /** @nullable */
  standards?: string[];
  /** @nullable */
  verificationMethods?: string[];
}
