/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type EstimatedNumberOfPeopleFP = typeof EstimatedNumberOfPeopleFP[keyof typeof EstimatedNumberOfPeopleFP];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EstimatedNumberOfPeopleFP = {
  ZeroToFiveHundred: 'ZeroToFiveHundred',
  FiveHundredToOneK: 'FiveHundredToOneK',
  OneKToFiveK: 'OneKToFiveK',
  FiveKToTenK: 'FiveKToTenK',
  TenKToFiftyK: 'TenKToFiftyK',
  FiftyKToHundredK: 'FiftyKToHundredK',
  HundredKPlus: 'HundredKPlus',
  Unsure: 'Unsure',
} as const;
