/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type EstimatedNumberOfPeople = typeof EstimatedNumberOfPeople[keyof typeof EstimatedNumberOfPeople];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EstimatedNumberOfPeople = {
  OneToTenK: 'OneToTenK',
  TenKToFiftyK: 'TenKToFiftyK',
  FiftyKToHundredK: 'FiftyKToHundredK',
  HundredKPlus: 'HundredKPlus',
  Unsure: 'Unsure',
} as const;
