/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type EventType = (typeof EventType)[keyof typeof EventType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventType = {
  GroundBreaking: 'GroundBreaking',
  RibbonCuttingOpening: 'RibbonCuttingOpening',
  CommunityEngagement: 'CommunityEngagement',
  Other: 'Other',
} as const;
