/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type EventStatus = typeof EventStatus[keyof typeof EventStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventStatus = {
  NotPlanned: 'NotPlanned',
  PlannedDateUnknown: 'PlannedDateUnknown',
  PlannedDateKnown: 'PlannedDateKnown',
  AlreadyOccurred: 'AlreadyOccurred',
  Unknown: 'Unknown',
} as const;
