/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { PastEvent } from './pastEvent';
import type { ProjectEvent } from './projectEvent';

export interface EventInformation {
  /** @nullable */
  anyUpcomingEvents?: boolean;
  /** @nullable */
  eventsOccurredSinceLastReport?: boolean;
  /** @nullable */
  pastEvents?: PastEvent[];
  /** @nullable */
  upcomingEvents?: ProjectEvent[];
}
