/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectEvent } from './projectEvent';

export interface EventInformation {
  pastEvents?: ProjectEvent[];
  /** @nullable */
  futureEvents?: ProjectEvent[];
  /** @nullable */
  haveEventsOccurred?: boolean;
}
