/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentType } from './documentType';

export interface FileData {
  applicationId?: string;
  content?: string;
  contentType?: string;
  documentType?: DocumentType;
  name?: string;
}
