/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentType } from './documentType';
import type { RecordType } from './recordType';

export interface FileData {
  content?: string;
  contentType?: string;
  documentType?: DocumentType;
  name?: string;
  recordId?: string;
  recordType?: RecordType;
}
