/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { ForecastStatus } from './forecastStatus';

export interface ForecastDetails {
  /** @nullable */
  forecastAmount?: number;
  /** @nullable */
  forecastDate?: string;
  /** @nullable */
  forecastType?: string;
  /** @nullable */
  id?: string;
  /** @nullable */
  status?: ForecastStatus;
}
