/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type FormType = (typeof FormType)[keyof typeof FormType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FormType = {
  Application: 'Application',
  Report: 'Report',
} as const;
