/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type FpApplicationAllOf = {
  /** @nullable */
  authorizedRepresentativeStatement?: boolean;
  /** @nullable */
  informationAccuracyStatement?: boolean;
};
