/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { DraftFpApplication } from './draftFpApplication';
import type { FpApplicationAllOf } from './fpApplicationAllOf';

export type FpApplication = DraftFpApplication & FpApplicationAllOf;
