/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { SignageType } from './signageType';

export interface FundingSignage {
  /** @nullable */
  beenApproved?: boolean;
  /** @nullable */
  dateInstalled?: string;
  /** @nullable */
  dateRemoved?: string;
  /** @nullable */
  id?: string;
  /** @nullable */
  type?: SignageType;
}
