/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type FundingType = typeof FundingType[keyof typeof FundingType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FundingType = {
  Fed: 'Fed',
  FedProv: 'FedProv',
  Prov: 'Prov',
  SelfFunding: 'SelfFunding',
  OtherGrants: 'OtherGrants',
} as const;
