/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { FundingType } from './fundingType';

export interface FundingInformation {
  /**
   * @minimum 0
   * @maximum 999999999.99
   * @nullable
   */
  amount?: number;
  /** @nullable */
  name?: string;
  /** @nullable */
  otherDescription?: string;
  /** @nullable */
  type?: FundingType;
}
