/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export interface InfrastructureImpacted {
  /** @nullable */
  impact?: string;
  /** @nullable */
  infrastructure?: string;
}
