/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type InterimProjectType =
  (typeof InterimProjectType)[keyof typeof InterimProjectType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InterimProjectType = {
  Stream1: 'Stream1',
  Stream2: 'Stream2',
} as const;
