/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type InterimReportStatus = typeof InterimReportStatus[keyof typeof InterimReportStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InterimReportStatus = {
  Pending: 'Pending',
  Review: 'Review',
  Approved: 'Approved',
  Rejected: 'Rejected',
} as const;
