/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { Forecast } from './forecast';
import type { PeriodType } from './periodType';
import type { ProgressReport } from './progressReport';
import type { ProjectClaim } from './projectClaim';
import type { InterimProjectType } from './interimProjectType';
import type { InterimReportStatus } from './interimReportStatus';

export interface InterimReport {
  /** @nullable */
  description?: string;
  /** @nullable */
  dueDate?: string;
  /** @nullable */
  forecast?: Forecast;
  /** @nullable */
  id?: string;
  /** @nullable */
  periodType?: PeriodType;
  /** @nullable */
  progressReport?: ProgressReport;
  /** @nullable */
  projectClaim?: ProjectClaim;
  /** @nullable */
  projectType?: InterimProjectType;
  /** @nullable */
  status?: InterimReportStatus;
}
