/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { ForecastDetails } from './forecastDetails';
import type { PeriodType } from './periodType';
import type { ProgressReportDetails } from './progressReportDetails';
import type { ClaimDetails } from './claimDetails';
import type { InterimProjectType } from './interimProjectType';
import type { InterimReportStatus } from './interimReportStatus';

export interface InterimReportDetails {
  /** @nullable */
  description?: string;
  /** @nullable */
  dueDate?: string;
  /** @nullable */
  forecast?: ForecastDetails;
  /** @nullable */
  id?: string;
  /** @nullable */
  periodType?: PeriodType;
  /** @nullable */
  progressReport?: ProgressReportDetails;
  /** @nullable */
  projectClaim?: ClaimDetails;
  /** @nullable */
  projectType?: InterimProjectType;
  /** @nullable */
  status?: InterimReportStatus;
}
