/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type InterimReportStatus = typeof InterimReportStatus[keyof typeof InterimReportStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InterimReportStatus = {
  NotStarted: 'NotStarted',
  InProgress: 'InProgress',
  Approved: 'Approved',
  Skipped: 'Skipped',
} as const;
