/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export interface OidcConfiguration {
  clientId?: string;
  clientSecret?: string;
  issuer?: string;
  postLogoutRedirectUrl?: string;
  scope?: string;
}
