/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { PaymentConditionStatus } from './paymentConditionStatus';

export interface PaymentCondition {
  /** @nullable */
  conditionName?: string;
  /** @nullable */
  dateMet?: string;
  /** @nullable */
  id?: string;
  /** @nullable */
  limit?: number;
  /** @nullable */
  status?: PaymentConditionStatus;
}
