/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type PaymentConditionStatus = typeof PaymentConditionStatus[keyof typeof PaymentConditionStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentConditionStatus = {
  Met: 'Met',
  NotMet: 'NotMet',
} as const;
