/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export interface PaymentCondition {
  /** @nullable */
  conditionMet?: boolean;
  /** @nullable */
  conditionName?: string;
  /** @nullable */
  dateMet?: string;
  /** @nullable */
  id?: string;
  /** @nullable */
  limit?: number;
}
