/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type PeriodType = (typeof PeriodType)[keyof typeof PeriodType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PeriodType = {
  Periodical: 'Periodical',
  Final: 'Final',
  Interim: 'Interim',
} as const;
