/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export interface ProfileDetails {
  /** @nullable */
  department?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  /** @nullable */
  phone?: string;
  /** @nullable */
  title?: string;
}
