/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export interface ProfileDetails {
  businessName?: string;
  /** @nullable */
  department?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  /** @nullable */
  phone?: string;
  /** @nullable */
  title?: string;
}
