/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type ProgramType = typeof ProgramType[keyof typeof ProgramType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProgramType = {
  DRIF: 'DRIF',
} as const;
