/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { ProgressReportStatus } from './progressReportStatus';
import type { WorkPlan } from './workPlan';

export interface ProgressReport {
  /** @nullable */
  dateApproved?: string;
  /** @nullable */
  dateSubmitted?: string;
  /** @nullable */
  dueDate?: string;
  /** @nullable */
  id?: string;
  /** @nullable */
  status?: ProgressReportStatus;
  /** @nullable */
  workPlan?: WorkPlan;
}
