/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { EventInformation } from './eventInformation';
import type { InterimProjectType } from './interimProjectType';
import type { ProgressReportStatus } from './progressReportStatus';
import type { Workplan } from './workplan';

export interface ProgressReport {
  /** @nullable */
  dateApproved?: string;
  /** @nullable */
  dateSubmitted?: string;
  /** @nullable */
  dueDate?: string;
  /** @nullable */
  eventInformation?: EventInformation;
  /** @nullable */
  id?: string;
  /** @nullable */
  projectType?: InterimProjectType;
  /** @nullable */
  status?: ProgressReportStatus;
  /** @nullable */
  workplan?: Workplan;
}
