/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { ProgressReportStatus } from './progressReportStatus';

export interface ProgressReport {
  /** @nullable */
  id?: string;
  /** @nullable */
  reportDate?: string;
  /** @nullable */
  reportType?: string;
  /** @nullable */
  status?: ProgressReportStatus;
}
