/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type ProjectProgressStatus =
  (typeof ProjectProgressStatus)[keyof typeof ProjectProgressStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectProgressStatus = {
  OnSchedule: 'OnSchedule',
  AheadOfSchedule: 'AheadOfSchedule',
  BehindSchedule: 'BehindSchedule',
  Complete: 'Complete',
} as const;
