/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { EventStatus } from './eventStatus';

export interface ProjectEvent {
  /** @nullable */
  status?: EventStatus;
}
