/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type ProjectType = typeof ProjectType[keyof typeof ProjectType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectType = {
  New: 'New',
  Existing: 'Existing',
} as const;
