/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { ClaimStatus } from './claimStatus';

export interface ProjectClaim {
  /** @nullable */
  claimAmount?: number;
  /** @nullable */
  claimDate?: string;
  /** @nullable */
  claimType?: string;
  /** @nullable */
  id?: string;
  /** @nullable */
  status?: ClaimStatus;
}
