/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { ContactDetails } from './contactDetails';
import type { EventStatus } from './eventStatus';
import type { EventType } from './eventType';

export interface ProjectEvent {
  /** @nullable */
  actualEventDate?: string;
  /** @nullable */
  eventContact?: ContactDetails;
  /** @nullable */
  id?: string;
  /** @nullable */
  nextEventDescription?: string;
  /** @nullable */
  plannedEventDate?: string;
  /** @nullable */
  provincialRepresentativeRequest?: boolean;
  /** @nullable */
  provincialRepresentativeRequestComment?: string;
  /** @nullable */
  status?: EventStatus;
  /** @nullable */
  type?: EventType;
}
