/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type ProjectProgress = typeof ProjectProgress[keyof typeof ProjectProgress];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectProgress = {
  OnSchedule: 'OnSchedule',
  AheadOfSchedule: 'AheadOfSchedule',
  BehindSchedule: 'BehindSchedule',
  Complete: 'Complete',
} as const;
