/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { ContactDetails } from './contactDetails';

export interface ProjectEvent {
  /** @nullable */
  contact?: ContactDetails;
  /** @nullable */
  date?: string;
  /** @nullable */
  details?: string;
  /** @nullable */
  id?: string;
  /** @nullable */
  provincialRepresentativeRequest?: boolean;
}
