/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export interface ProposedActivity {
  /** @nullable */
  end?: string;
  /** @nullable */
  name?: string;
  /** @nullable */
  relatedMilestone?: string;
  /** @nullable */
  start?: string;
}
