/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type ProponentType = (typeof ProponentType)[keyof typeof ProponentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProponentType = {
  FirstNation: 'FirstNation',
  LocalGovernment: 'LocalGovernment',
  RegionalDistrict: 'RegionalDistrict',
} as const;
