/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export interface ProposedActivity {
  /** @nullable */
  deliverables?: string;
  /** @nullable */
  endDate?: string;
  /** @nullable */
  name?: string;
  /** @nullable */
  preCreatedActivity?: boolean;
  /** @nullable */
  startDate?: string;
  /** @nullable */
  tasks?: string;
}
