/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export interface ProposedActivity {
  /** @nullable */
  endDate?: string;
  /** @nullable */
  name?: string;
  /** @nullable */
  relatedMilestone?: string;
  /** @nullable */
  startDate?: string;
}
