/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type ProvincialMedia = typeof ProvincialMedia[keyof typeof ProvincialMedia];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProvincialMedia = {
  NotAnnounced: 'NotAnnounced',
  NotApplicable: 'NotApplicable',
} as const;
