/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export interface QueryOptions {
  /** @nullable */
  filter?: string;
  /** @nullable */
  orderBy?: string;
  /** @nullable */
  page?: number;
  /** @nullable */
  pageSize?: number;
}
