/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type RecordType = (typeof RecordType)[keyof typeof RecordType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RecordType = {
  FullProposal: 'FullProposal',
  ProgressReport: 'ProgressReport',
} as const;
