/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type ReportingScheduleType =
  (typeof ReportingScheduleType)[keyof typeof ReportingScheduleType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReportingScheduleType = {
  Quarterly: 'Quarterly',
  Monthly: 'Monthly',
} as const;
