/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type ReportType = (typeof ReportType)[keyof typeof ReportType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReportType = {
  OffCycle: 'OffCycle',
  Interim: 'Interim',
  Final: 'Final',
} as const;
