/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type ResourceCategory = typeof ResourceCategory[keyof typeof ResourceCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResourceCategory = {
  Category1: 'Category1',
  Category2: 'Category2',
  Category3: 'Category3',
} as const;
