/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type ResourceCategory = typeof ResourceCategory[keyof typeof ResourceCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResourceCategory = {
  ProjectManager: 'ProjectManager',
  CulturalMonitor: 'CulturalMonitor',
  Elders: 'Elders',
  JuniorQualifiedProfessional: 'JuniorQualifiedProfessional',
  IntermediateQualifiedProfessional: 'IntermediateQualifiedProfessional',
  SeniorQualifiedProfessional: 'SeniorQualifiedProfessional',
  PrincipalQualifiedProfessional: 'PrincipalQualifiedProfessional',
  ProjectSupport: 'ProjectSupport',
  Equipment: 'Equipment',
  Other: 'Other',
} as const;
