/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { FileMetadata } from './fileMetadata';

export interface S3File {
  content?: string;
  contentType?: string;
  fileName?: string;
  metadata?: FileMetadata[];
}
