/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { YesNoOption } from './yesNoOption';

export interface ScreenerQuestions {
  /** @nullable */
  costEstimate?: boolean;
  /** @nullable */
  engagedWithFirstNationsOccurred?: boolean;
  /** @nullable */
  firstNationsAuthorizedByPartners?: YesNoOption;
  /** @nullable */
  foundationWorkCompleted?: YesNoOption;
  /** @nullable */
  haveAuthorityToDevelop?: boolean;
  /** @nullable */
  incorporateFutureClimateConditions?: boolean;
  /** @nullable */
  localGovernmentAuthorizedByPartners?: YesNoOption;
  /** @nullable */
  meetsEligibilityRequirements?: boolean;
  /** @nullable */
  meetsRegulatoryRequirements?: boolean;
  /** @nullable */
  projectSchedule?: boolean;
  /** @nullable */
  projectWorkplan?: boolean;
  /** @nullable */
  sitePlan?: YesNoOption;
}
