/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type SignageType = typeof SignageType[keyof typeof SignageType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SignageType = {
  Temporary: 'Temporary',
  Digital: 'Digital',
  Plaque: 'Plaque',
} as const;
