/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type SubmissionPortalStatus = typeof SubmissionPortalStatus[keyof typeof SubmissionPortalStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SubmissionPortalStatus = {
  Draft: 'Draft',
  UnderReview: 'UnderReview',
  Ineligible: 'Ineligible',
  EligiblePending: 'EligiblePending',
  EligibleInvited: 'EligibleInvited',
  Withdrawn: 'Withdrawn',
  Closed: 'Closed',
  FullProposalSubmitted: 'FullProposalSubmitted',
  Approved: 'Approved',
  ApprovedInPrinciple: 'ApprovedInPrinciple',
  Deleted: 'Deleted',
} as const;
