/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { DelayReason } from './delayReason';
import type { FundingSignage } from './fundingSignage';
import type { ProjectProgress } from './projectProgress';
import type { WorkplanActivity } from './workplanActivity';

export interface Workplan {
  /** @nullable */
  aheadOfScheduleComments?: string;
  /** @nullable */
  behindScheduleMitigatingComments?: string;
  /** @nullable */
  constructionCompletionPercentage?: number;
  /** @nullable */
  delayReason?: DelayReason;
  /** @nullable */
  fundingSignage?: FundingSignage[];
  /** @nullable */
  fundingSourcesChanged?: boolean;
  /** @nullable */
  fundingSourcesChangedComment?: string;
  /** @nullable */
  mediaAnnouncement?: boolean;
  /** @nullable */
  mediaAnnouncementComment?: string;
  /** @nullable */
  mediaAnnouncementDate?: string;
  /** @nullable */
  otherDelayReason?: string;
  /** @nullable */
  outstandingIssues?: boolean;
  /** @nullable */
  outstandingIssuesComments?: string;
  /** @nullable */
  projectCompletionPercentage?: number;
  /** @nullable */
  projectProgress?: ProjectProgress;
  /** @nullable */
  signageNotRequiredComments?: string;
  /** @nullable */
  signageRequired?: boolean;
  /** @nullable */
  workplanActivities?: WorkplanActivity[];
}
