/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { Delay } from './delay';
import type { FundingSignage } from './fundingSignage';
import type { ProjectProgressStatus } from './projectProgressStatus';
import type { WorkplanActivity } from './workplanActivity';

export interface Workplan {
  /**
   * @minLength 0
   * @maxLength 2000
   * @nullable
   */
  aheadOfScheduleComments?: string;
  /**
   * @minLength 0
   * @maxLength 2000
   * @nullable
   */
  behindScheduleMitigatingComments?: string;
  /**
   * @minimum 0
   * @maximum 100
   * @nullable
   */
  constructionCompletionPercentage?: number;
  /** @nullable */
  delayReason?: Delay;
  /** @nullable */
  fundingSignage?: FundingSignage[];
  /** @nullable */
  fundingSourcesChanged?: boolean;
  /**
   * @minLength 0
   * @maxLength 2000
   * @nullable
   */
  fundingSourcesChangedComment?: string;
  /** @nullable */
  mediaAnnouncement?: boolean;
  /** @nullable */
  mediaAnnouncementComment?: string;
  /** @nullable */
  mediaAnnouncementDate?: string;
  /**
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  otherDelayReason?: string;
  /** @nullable */
  outstandingIssues?: boolean;
  /**
   * @minLength 0
   * @maxLength 2000
   * @nullable
   */
  outstandingIssuesComments?: string;
  /**
   * @minimum 0
   * @maximum 100
   * @nullable
   */
  projectCompletionPercentage?: number;
  /** @nullable */
  projectProgress?: ProjectProgressStatus;
  /**
   * @minLength 0
   * @maxLength 50
   * @nullable
   */
  signageNotRequiredComments?: string;
  /** @nullable */
  signageRequired?: boolean;
  /** @nullable */
  workplanActivities?: WorkplanActivity[];
}
