/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { ActivityType } from './activityType';
import type { WorkplanStatus } from './workplanStatus';

export interface WorkplanActivity {
  /** @nullable */
  activity?: ActivityType;
  /** @nullable */
  actualCompletionDate?: string;
  /** @nullable */
  actualStartDate?: string;
  /** @nullable */
  comment?: string;
  /** @nullable */
  id?: string;
  /** @nullable */
  isMandatory?: boolean;
  /** @nullable */
  plannedCompletionDate?: string;
  /** @nullable */
  plannedStartDate?: string;
  /** @nullable */
  preCreatedActivity?: boolean;
  /** @nullable */
  status?: WorkplanStatus;
}
