/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { YesNoOption } from './yesNoOption';
import type { ProvincialMedia } from './provincialMedia';
import type { WorkplanActivity } from './workplanActivity';

export interface Workplan {
  /** @nullable */
  communityMedia?: YesNoOption;
  /** @nullable */
  communityMediaComment?: string;
  /** @nullable */
  communityMediaDate?: string;
  /** @nullable */
  fundingSourcesChanged?: boolean;
  /** @nullable */
  fundingSourcesChangedComment?: string;
  /** @nullable */
  outstandingIssues?: string;
  /** @nullable */
  projectCompletionPercentage?: number;
  /** @nullable */
  provincialMedia?: ProvincialMedia;
  /** @nullable */
  provincialMediaComment?: string;
  /** @nullable */
  provincialMediaDate?: string;
  /** @nullable */
  workplanActivities?: WorkplanActivity[];
  /** @nullable */
  worksCompleted?: string;
}
