/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type WorkplanStatus =
  (typeof WorkplanStatus)[keyof typeof WorkplanStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkplanStatus = {
  NotStarted: 'NotStarted',
  InProgress: 'InProgress',
  Completed: 'Completed',
  Awarded: 'Awarded',
  NotAwarded: 'NotAwarded',
  NoLongerNeeded: 'NoLongerNeeded',
} as const;
