/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { WorkplanActivity } from './workplanActivity';

export interface Workplan {
  /** @nullable */
  fundingSourcesChanged?: boolean;
  /** @nullable */
  fundingSourcesChangedComment?: string;
  /** @nullable */
  outstandingIssues?: boolean;
  outstandingIssuesComment?: string;
  /** @nullable */
  mediaAnnouncement?: boolean;
  /** @nullable */
  mediaAnnouncementComment?: string;
  /** @nullable */
  mediaAnnouncementDate?: string;
  /** @nullable */
  projectCompletionPercentage?: number;
  /** @nullable */
  workplanActivities?: WorkplanActivity[];
  /** @nullable */
  worksCompleted?: string;
}
