/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import type { WorkplanProgress } from './workplanProgress';

export interface WorkplanActivity {
  /** @nullable */
  progress?: WorkplanProgress;
}
