/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export type WorkplanProgress = typeof WorkplanProgress[keyof typeof WorkplanProgress];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkplanProgress = {
  NotStarted: 'NotStarted',
  InProgress: 'InProgress',
  Completed: 'Completed',
  NotApplicable: 'NotApplicable',
} as const;
