/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */

export interface YearOverYearFunding {
  /**
   * @minimum 0
   * @maximum 999999999.99
   * @nullable
   */
  amount?: number;
  /** @nullable */
  year?: string;
}
