/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * DRR API
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http'
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http'
import {
  Injectable
} from '@angular/core'
import {
  Observable
} from 'rxjs'
import type {
  DraftDrrProject,
  DrrProject,
  Forecast,
  InterimReport,
  ProgressReport,
  ProgressReportResult,
  ProjectClaim,
  ProjectResponse,
  ProjectResult,
  ProjectUpdateProgressReportParams
} from '../../model'


type HttpClientOptions = {
  headers?: HttpHeaders | {
      [header: string]: string | string[];
  };
  context?: HttpContext;
  observe?: any;
  params?: HttpParams | {
    [param: string]: string | number | boolean | ReadonlyArray<string | number | boolean>;
  };
  reportProgress?: boolean;
  responseType?: any;
  withCredentials?: boolean;
};



@Injectable({ providedIn: 'root' })
export class ProjectService {
  constructor(
    private http: HttpClient,
  ) {} projectGet<TData = ProjectResponse>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    projectGet<TData = ProjectResponse>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    projectGet<TData = ProjectResponse>(
     options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;projectGet<TData = ProjectResponse>(
     options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `/api/project`,options
    );
  }
 projectGetProject<TData = DraftDrrProject>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    projectGetProject<TData = DraftDrrProject>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    projectGetProject<TData = DraftDrrProject>(
    id: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;projectGetProject<TData = DraftDrrProject>(
    id: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `/api/project/${id}`,options
    );
  }
 projectUpdateProject<TData = ProjectResult>(
    id: string,
    draftDrrProject: DraftDrrProject, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    projectUpdateProject<TData = ProjectResult>(
    id: string,
    draftDrrProject: DraftDrrProject, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    projectUpdateProject<TData = ProjectResult>(
    id: string,
    draftDrrProject: DraftDrrProject, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;projectUpdateProject<TData = ProjectResult>(
    id: string,
    draftDrrProject: DraftDrrProject, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `/api/project/${id}`,
      draftDrrProject,options
    );
  }
 projectSubmitProject<TData = ProjectResult>(
    id: string,
    drrProject: DrrProject, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    projectSubmitProject<TData = ProjectResult>(
    id: string,
    drrProject: DrrProject, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    projectSubmitProject<TData = ProjectResult>(
    id: string,
    drrProject: DrrProject, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;projectSubmitProject<TData = ProjectResult>(
    id: string,
    drrProject: DrrProject, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.post<TData>(
      `/api/project/${id}/submit`,
      drrProject,options
    );
  }
 projectGetInterimReport<TData = InterimReport>(
    projectId: string,
    reportId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    projectGetInterimReport<TData = InterimReport>(
    projectId: string,
    reportId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    projectGetInterimReport<TData = InterimReport>(
    projectId: string,
    reportId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;projectGetInterimReport<TData = InterimReport>(
    projectId: string,
    reportId: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `/api/project/${projectId}/interim-reports/${reportId}`,options
    );
  }
 projectGetClaim<TData = ProjectClaim>(
    projectId: string,
    reportId: string,
    claimId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    projectGetClaim<TData = ProjectClaim>(
    projectId: string,
    reportId: string,
    claimId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    projectGetClaim<TData = ProjectClaim>(
    projectId: string,
    reportId: string,
    claimId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;projectGetClaim<TData = ProjectClaim>(
    projectId: string,
    reportId: string,
    claimId: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `/api/project/${projectId}/interim-reports/${reportId}/claims/${claimId}`,options
    );
  }
 projectGetProgressReport<TData = ProgressReport>(
    projectId: string,
    reportId: string,
    progressId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    projectGetProgressReport<TData = ProgressReport>(
    projectId: string,
    reportId: string,
    progressId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    projectGetProgressReport<TData = ProgressReport>(
    projectId: string,
    reportId: string,
    progressId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;projectGetProgressReport<TData = ProgressReport>(
    projectId: string,
    reportId: string,
    progressId: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `/api/project/${projectId}/interim-reports/${reportId}/progress-reports/${progressId}`,options
    );
  }
 projectUpdateProgressReport<TData = ProgressReportResult>(
    projectId: string,
    reportId: string,
    progressId: string,
    progressReport: ProgressReport,
    params?: ProjectUpdateProgressReportParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    projectUpdateProgressReport<TData = ProgressReportResult>(
    projectId: string,
    reportId: string,
    progressId: string,
    progressReport: ProgressReport,
    params?: ProjectUpdateProgressReportParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    projectUpdateProgressReport<TData = ProgressReportResult>(
    projectId: string,
    reportId: string,
    progressId: string,
    progressReport: ProgressReport,
    params?: ProjectUpdateProgressReportParams, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;projectUpdateProgressReport<TData = ProgressReportResult>(
    projectId: string,
    reportId: string,
    progressId: string,
    progressReport: ProgressReport,
    params?: ProjectUpdateProgressReportParams, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.patch<TData>(
      `/api/project/${projectId}/interim-reports/${reportId}/progress-reports/${progressId}`,
      progressReport,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
 projectGetForecastReport<TData = Forecast>(
    projectId: string,
    reportId: string,
    forecastId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'body' }
  ): Observable<TData>;
    projectGetForecastReport<TData = Forecast>(
    projectId: string,
    reportId: string,
    forecastId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
    projectGetForecastReport<TData = Forecast>(
    projectId: string,
    reportId: string,
    forecastId: string, options?: Omit<HttpClientOptions, 'observe'> & { observe?: 'events' }
  ): Observable<HttpEvent<TData>>;projectGetForecastReport<TData = Forecast>(
    projectId: string,
    reportId: string,
    forecastId: string, options?: HttpClientOptions
  ): Observable<TData>  {
    return this.http.get<TData>(
      `/api/project/${projectId}/interim-reports/${reportId}/forecasts/${forecastId}`,options
    );
  }
};

export type ProjectGetClientResult = NonNullable<ProjectResponse>
export type ProjectGetProjectClientResult = NonNullable<DraftDrrProject>
export type ProjectUpdateProjectClientResult = NonNullable<ProjectResult>
export type ProjectSubmitProjectClientResult = NonNullable<ProjectResult>
export type ProjectGetInterimReportClientResult = NonNullable<InterimReport>
export type ProjectGetClaimClientResult = NonNullable<ProjectClaim>
export type ProjectGetProgressReportClientResult = NonNullable<ProgressReport>
export type ProjectUpdateProgressReportClientResult = NonNullable<ProgressReportResult>
export type ProjectGetForecastReportClientResult = NonNullable<Forecast>
